[phases.setup]
nixPkgs = ["nodejs_20", "fonts-noto-color-emoji", "fontconfig"]

[phases.build]
cmds = [
  "mkdir -p /root/.local/share/fonts",
  "cp src/assets/fonts/*.ttf /root/.local/share/fonts/ || true",
  "fc-cache -f",
  "npm run build"
]

[start]
cmd = "npm run start"
